import { createClient } from "@/lib/supabase/server"
import { redirect } from "next/navigation"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { BookMarked } from "lucide-react"

export default async function HomePage() {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (user) {
    redirect("/dashboard")
  }

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-b from-background to-muted/20 px-4">
      <div className="max-w-2xl text-center space-y-8">
        <div className="flex justify-center">
          <div className="p-4 bg-primary/10 rounded-full">
            <BookMarked className="h-16 w-16 text-primary" />
          </div>
        </div>

        <div className="space-y-4">
          <h1 className="text-5xl font-bold tracking-tight text-balance">Save Articles to Read Later</h1>
          <p className="text-xl text-muted-foreground text-pretty">
            Build your personal reading list with AI-powered summaries and smart search. Never lose track of great
            content again.
          </p>
        </div>

        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Button asChild size="lg">
            <Link href="/auth/sign-up">Get Started</Link>
          </Button>
          <Button asChild variant="outline" size="lg">
            <Link href="/auth/login">Sign In</Link>
          </Button>
        </div>

        <div className="pt-8 grid grid-cols-1 sm:grid-cols-3 gap-6 text-left">
          <div className="space-y-2">
            <div className="text-4xl">🔖</div>
            <h3 className="font-semibold">Save Instantly</h3>
            <p className="text-sm text-muted-foreground">Paste any URL and we'll extract the content for you</p>
          </div>
          <div className="space-y-2">
            <div className="text-4xl">✨</div>
            <h3 className="font-semibold">AI Summaries</h3>
            <p className="text-sm text-muted-foreground">Get concise summaries generated by AI</p>
          </div>
          <div className="space-y-2">
            <div className="text-4xl">🔍</div>
            <h3 className="font-semibold">Smart Search</h3>
            <p className="text-sm text-muted-foreground">Find articles with semantic search</p>
          </div>
        </div>
      </div>
    </div>
  )
}
